//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongGYMv1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLyPhongGYMv1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _00cd8eabf948d596af53e10361a99928 {
            get {
                object obj = ResourceManager.GetObject("00cd8eabf948d596af53e10361a99928", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _173cbb3366ba0142d6a4284176d122e4 {
            get {
                object obj = ResourceManager.GetObject("173cbb3366ba0142d6a4284176d122e4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_116664 {
            get {
                object obj = ResourceManager.GetObject("2_116664", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2ea6370268aec1df9efbe27b623a5c5a {
            get {
                object obj = ResourceManager.GetObject("2ea6370268aec1df9efbe27b623a5c5a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2ea6370268aec1df9efbe27b623a5c5a1 {
            get {
                object obj = ResourceManager.GetObject("2ea6370268aec1df9efbe27b623a5c5a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2ea6370268aec1df9efbe27b623a5c5a2 {
            get {
                object obj = ResourceManager.GetObject("2ea6370268aec1df9efbe27b623a5c5a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _313dcca7f22b5bce15523235329bc562 {
            get {
                object obj = ResourceManager.GetObject("313dcca7f22b5bce15523235329bc562", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _313dcca7f22b5bce15523235329bc5621 {
            get {
                object obj = ResourceManager.GetObject("313dcca7f22b5bce15523235329bc5621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _333b704f5d130b6a3152f5a07e79c899 {
            get {
                object obj = ResourceManager.GetObject("333b704f5d130b6a3152f5a07e79c899", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _53e801fcbab23aaae1158b81bfe64a94 {
            get {
                object obj = ResourceManager.GetObject("53e801fcbab23aaae1158b81bfe64a94", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _53e801fcbab23aaae1158b81bfe64a941 {
            get {
                object obj = ResourceManager.GetObject("53e801fcbab23aaae1158b81bfe64a941", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _53e801fcbab23aaae1158b81bfe64a942 {
            get {
                object obj = ResourceManager.GetObject("53e801fcbab23aaae1158b81bfe64a942", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _53e801fcbab23aaae1158b81bfe64a943 {
            get {
                object obj = ResourceManager.GetObject("53e801fcbab23aaae1158b81bfe64a943", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _53e801fcbab23aaae1158b81bfe64a944 {
            get {
                object obj = ResourceManager.GetObject("53e801fcbab23aaae1158b81bfe64a944", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _545e135e83a4cc4eed986c40cd2bddd9 {
            get {
                object obj = ResourceManager.GetObject("545e135e83a4cc4eed986c40cd2bddd9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _62b4d47e88a1de19bc489616e24e4cc4 {
            get {
                object obj = ResourceManager.GetObject("62b4d47e88a1de19bc489616e24e4cc4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _69535afa8c3803ed4fb3bd5a38290e45 {
            get {
                object obj = ResourceManager.GetObject("69535afa8c3803ed4fb3bd5a38290e45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _69535afa8c3803ed4fb3bd5a38290e451 {
            get {
                object obj = ResourceManager.GetObject("69535afa8c3803ed4fb3bd5a38290e451", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap account_username_people_avatar_profile_person_user_icon_258905 {
            get {
                object obj = ResourceManager.GetObject("account_username_people_avatar_profile_person_user_icon_258905", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anastase_maragos_7kEpUPB8vNk_unsplash {
            get {
                object obj = ResourceManager.GetObject("anastase-maragos-7kEpUPB8vNk-unsplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anastase_maragos_7kEpUPB8vNk_unsplash1 {
            get {
                object obj = ResourceManager.GetObject("anastase-maragos-7kEpUPB8vNk-unsplash1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b23fff5386d16a8bcb425921dbff847f {
            get {
                object obj = ResourceManager.GetObject("b23fff5386d16a8bcb425921dbff847f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b68fb7dfe0636a8da1afad02f10e1e65 {
            get {
                object obj = ResourceManager.GetObject("b68fb7dfe0636a8da1afad02f10e1e65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b8b9ff98d24aa10f3b37526eb3a111ee {
            get {
                object obj = ResourceManager.GetObject("b8b9ff98d24aa10f3b37526eb3a111ee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bf12e234cd5b0783089209226465822e {
            get {
                object obj = ResourceManager.GetObject("bf12e234cd5b0783089209226465822e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clock_icon_png_10761 {
            get {
                object obj = ResourceManager.GetObject("clock-icon-png-10761", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diary_icon_46561 {
            get {
                object obj = ResourceManager.GetObject("diary-icon-46561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ed5dbc8b9f78c09e4b52ddf9c6d5b2bb {
            get {
                object obj = ResourceManager.GetObject("ed5dbc8b9f78c09e4b52ddf9c6d5b2bb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f226d572737a4b4a071b6808bbd6add6 {
            get {
                object obj = ResourceManager.GetObject("f226d572737a4b4a071b6808bbd6add6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f226d572737a4b4a071b6808bbd6add6__1_ {
            get {
                object obj = ResourceManager.GetObject("f226d572737a4b4a071b6808bbd6add6 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f55148ad2ef92de8597008b60bcd29a8 {
            get {
                object obj = ResourceManager.GetObject("f55148ad2ef92de8597008b60bcd29a8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap head_icon_6522 {
            get {
                object obj = ResourceManager.GetObject("head-icon-6522", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap head_icon_65221 {
            get {
                object obj = ResourceManager.GetObject("head-icon-65221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_lock_4341303_120563 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-lock-4341303_120563", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_1 {
            get {
                object obj = ResourceManager.GetObject("images (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mobile_icon_png_2374 {
            get {
                object obj = ResourceManager.GetObject("mobile-icon-png-2374", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mobile_icon_png_23741 {
            get {
                object obj = ResourceManager.GetObject("mobile-icon-png-23741", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mobile_icon_png_23742 {
            get {
                object obj = ResourceManager.GetObject("mobile-icon-png-23742", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_icons_6113 {
            get {
                object obj = ResourceManager.GetObject("money-icons-6113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_icons_6123 {
            get {
                object obj = ResourceManager.GetObject("money-icons-6123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_icons_61231 {
            get {
                object obj = ResourceManager.GetObject("money-icons-61231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap money_icons_61232 {
            get {
                object obj = ResourceManager.GetObject("money-icons-61232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap profile_icon_png_909 {
            get {
                object obj = ResourceManager.GetObject("profile-icon-png-909", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap risen_wang_20jX9b35r_M_unsplash {
            get {
                object obj = ResourceManager.GetObject("risen-wang-20jX9b35r_M-unsplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap risen_wang_20jX9b35r_M_unsplash__1_ {
            get {
                object obj = ResourceManager.GetObject("risen-wang-20jX9b35r_M-unsplash (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sample_User_Icon {
            get {
                object obj = ResourceManager.GetObject("Sample_User_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap secure_icon_png_4995 {
            get {
                object obj = ResourceManager.GetObject("secure-icon-png-4995", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tải_xuống__1_ {
            get {
                object obj = ResourceManager.GetObject("tải xuống (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tạo_cho_tôi_ảnh_background__hệ_thống_GYM_QAT_FITNESS___ {
            get {
                object obj = ResourceManager.GetObject("tạo cho tôi ảnh background  hệ thống GYM QAT FITNESS . ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tạo_cho_tôi_ảnh_background__hệ_thống_GYM_QAT_FITNESS_1 {
            get {
                object obj = ResourceManager.GetObject("tạo cho tôi ảnh background  hệ thống GYM QAT FITNESS 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tạo_cho_tôi_background_về_Tập_Gym_với_tên_là__GYM_QAT_FITNESS_____hình_ảnh_là_phòng_tập_Gym_ngầu____thêm_con_hổ_vào {
            get {
                object obj = ResourceManager.GetObject("Tạo cho tôi background về Tập Gym với tên là _GYM QAT FITNESS _), hình ảnh là phò" +
                        "ng tập Gym ngầu  , thêm con hổ vào", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tạo_hình_nền_Thêm_Khách_Hàng_của_hệ_thống_GYM_QAT_FITNESS {
            get {
                object obj = ResourceManager.GetObject("tạo hình nền Thêm Khách Hàng của hệ thống GYM QAT FITNESS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tạo_hình_nền_Thêm_Khách_Hàng_của_hệ_thống_GYM_QAT_FITNESS1 {
            get {
                object obj = ResourceManager.GetObject("tạo hình nền Thêm Khách Hàng của hệ thống GYM QAT FITNESS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_avatar_people_man_person_icon_262044 {
            get {
                object obj = ResourceManager.GetObject("user_avatar_people_man_person_icon_262044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z6443662368954_9be038eedaa83c72a20e52ff0215dad0 {
            get {
                object obj = ResourceManager.GetObject("z6443662368954_9be038eedaa83c72a20e52ff0215dad0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
